### ISSUE TITLE
add_hat

### ISSUE THREAD

**Issue by LUOBO123LUOBO123** [LiuXiaolong19920720/Add-Christmas-Hat#3]
add_hat中的  predictor_path = "shape_predictor_5_face_landmarks.dat"是什么意思，shape_predictor_5_face_landmarks.dat是什么

**Comment by LiuXiaolong19920720** [comment]
@LUOBO123LUOBO123 shape_predictor_5_face_landmarks.dat是一个训练好的检测人脸关键点的模型。 可以返回五个关键点，分别是两个眼睛的眼角和鼻尖下方。

**Comment by LUOBO123LUOBO123** [comment]
嗯嗯，刚接触，知道了，我看网上现在用68的多




------------------ 原始邮件 ------------------
发件人: "LiuXiaolong";<notifications@github.com>;
发送时间: 2017年12月27日(星期三) 中午11:23
收件人: "LiuXiaolong19920720/Add-Christmas-Hat"<Add-Christmas-Hat@noreply.github.com>;
抄送: "萝卜，有你的个性。。。"<1141560408@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [LiuXiaolong19920720/Add-Christmas-Hat] add_hat (#3)




shape_predictor_5_face_landmarks.dat是一个训练好的检测人脸关键点的模型。 可以返回五个关键点，分别是两个眼睛的眼角和鼻尖下方。
